# Generated by Django 6.0.2 on 2026-02-14 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='response',
            name='staff',
        ),
        migrations.RenameField(
            model_name='grievance',
            old_name='description',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='responded_at',
            new_name='replied_at',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='message',
            new_name='reply',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='status',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
