# Generated by Django 6.0.2 on 2026-03-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_complaint_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
    ]
