# Generated by Django 6.0.2 on 2026-03-20 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_authority_grievanceattachment_grievancecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authority',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin')], default='student', max_length=15),
            preserve_default=False,
        ),
    ]
