# Generated by Django 6.0.2 on 2026-03-20 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_authority_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.grievancecategory'),
        ),
    ]
